### ISSUE TITLE
module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.

### ISSUE THREAD

**Issue by MartinBTM** [jtydhr88/ComfyUI-LayerDivider#1]
Traceback (most recent call last):
  File "/mnt/ComfyUI/custom_nodes/ComfyUI-LayerDivider/__init__.py", line 59, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
ModuleNotFoundError: No module named 'ComfyUI-LayerDivider.nodes'
## LayerDivider: installing dependencies done.
Skip /mnt/ComfyUI/custom_nodes/ComfyUI-LayerDivider module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.

How to solve this problem?

**Comment by jtydhr88** [comment]
Hi, likely you run it on Linux but I only have windows environment at this moment

**Comment by jtydhr88** [comment]
And I only test it on the default windows bundle

**Comment by MartinBTM** [comment]
sure， Thank you, will it support linux soon?

**Comment by jtydhr88** [comment]
Hi, yes, I might investigate next week

**Comment by TijuanaKez** [comment]
Any updates?

**Comment by jtydhr88** [comment]
![image](https://github.com/jtydhr88/ComfyUI-LayerDivider/assets/860985/a3bfe6e2-adf4-4442-9717-6646e65f43fe)
just make it working on Linux, the code is ok, but require some setting up, I will update doc soon

**Comment by jtydhr88** [comment]
I update the readme, and to run this repo in Linux, the key steps:
- pip install cython
- pip install pytoshop -I --no-cache-dir
- pip install psd_tools
- pip install onnxruntime-gpu==1.17.0 --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
make sure run them one by one.

Close this issue

**Comment by TijuanaKez** [comment]
> I update the readme, and to run this repo in Linux, the key steps:
> 
> * pip install cython
> * pip install pytoshop -I --no-cache-dir
> * pip install psd_tools
> * pip install onnxruntime-gpu==1.17.0 --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
>   make sure run them one by one.
> 
> Close this issue

Great news!
One thing I'm unsure of with your notes is creating the python environment.
Can the custom node have a different environment than the ComfyUI package itself? Because mine whole install has defaulted to Python 3.10, but I have Cuda 12.4. Everything else in Comfy works great.

"Assume you already have a python3.11 env + cuda 12.1". Would you say these versions are a hard requirement?

**Comment by jtydhr88** [comment]
@TijuanaKez I don't think these versions (py311 and cuda 12.1) are a hard requirement, but I only test this env on my local.
please feel free to open issue if you encounter the issue on your env
