### ISSUE TITLE
 i have a few suggestions

### ISSUE THREAD

**Issue by stephbertodk** [jtydhr88/ComfyUI-LayerDivider#3]
It would be great if there was a tooler that would allow us to make color changes on PNGs, count the number of colors, control the number of colors, and change the color in the area we mask. Nowadays, there are sites such as "online png tools" on the internet. You can also look at examples there. It would be completely different if the tools that would allow us to count and control the number of colors were on the comfyui screen.

**Comment by jtydhr88** [comment]
thanks for the feedback, I will take a look later
