### ISSUE TITLE
pytoshop wheels for python 3.10?

### ISSUE THREAD

**Issue by extra2AB** [jtydhr88/ComfyUI-LayerDivider#6]
majority of Installations use python 3.10. Especially if installed using Stability Matrix.

I searched for PreBuilt 310 wheels for pytoshop, but failed to find any.
I found one in an archive, but that seems to be deleted now.

Please provide a python 310 wheel

**Comment by extra2AB** [comment]
I managed to Manually install pytoshop successfully. But the Node still refuses to load.

**Comment by jtydhr88** [comment]
thanks for the infos

**Comment by extra2AB** [comment]
Nope, still so many errors occur like 

name 'packbits' is not defined
image has wrong mode

**Comment by jtydhr88** [comment]
I never try it on Stability Matrix, but I tested on two envs: 1. for python 310, I tested it on standalone conda env. 2. for python 311, I tested it on a new ComfyUI with default embedded python. both work well on my end.

**Comment by extra2AB** [comment]
I am trying that now.
backed up my virtual env, and created new.

cause similar thing happened with module insightface.

it just refused to install unless it is a fresh env, so I had to create new env, install it first, then everything else.

I am trying the same now. Will update if it works
