### ISSUE TITLE
ValueError: image has wrong mode

### ISSUE THREAD

**Issue by extra2AB** [jtydhr88/ComfyUI-LayerDivider#7]
out of the 2 workflows, the color base workflow works, but the segment mask workflow gives error saying Image has Wrong More

got prompt
[rgthree] Using rgthree's optimized recursive execution.
get_masks
masks
show_anns
!!! Exception during processing!!! image has wrong mode
Traceback (most recent call last):
File "D:\ai\stablediffusion\stablediffusion\Data\Packages\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\ai\stablediffusion\stablediffusion\Data\Packages\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\ai\stablediffusion\stablediffusion\Data\Packages\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\AI\StableDiffusion\StableDiffusion\Data\Packages\ComfyUI\custom_nodes\ComfyUI-LayerDivider\layer_divider_node.py", line 284, in execute
masked_image = show_anns(input_image, masks, output_dir)
File "D:\AI\StableDiffusion\StableDiffusion\Data\Packages\ComfyUI\custom_nodes\ComfyUI-LayerDivider\ldivider\ld_segment.py", line 65, in show_anns
base_mask = Image.alpha_composite(base_mask, Image.fromarray(mask))
File "D:\ai\stablediffusion\stablediffusion\Data\Packages\ComfyUI\venv\lib\site-packages\PIL\Image.py", line 3358, in alpha_composite
return im1._new(core.alpha_composite(im1.im, im2.im))
ValueError: image has wrong mode

**Comment by jtydhr88** [comment]
please share the image you are using

**Comment by extra2AB** [comment]
![image 1](https://github.com/jtydhr88/ComfyUI-LayerDivider/assets/47712756/34afbc2b-fb9b-486c-beda-fa255580d4cc)
![image 2](https://github.com/jtydhr88/ComfyUI-LayerDivider/assets/47712756/32d5fdf2-7f0d-44ea-abd1-6d91479bd3f3)

I tried more as well, but any image I try. I get same error.

I read online a bit and it said, they might be wrong extension, so I even opened in Photoshop and exported then as PNG (with alpha channel enabled) as well.

Still no luck

**Comment by jtydhr88** [comment]
thanks for sharing, I will test them later

**Comment by extra2AB** [comment]
any update ?

Also can you provide the example images as well, so I can be sure that there is no problem with the installation.

**Comment by jtydhr88** [comment]
Sorry, get busy this week, I will investigate on weekends and share my test images soon

**Comment by BarioIsCoding** [comment]
Use the `Images to Linear` node to first convert it correctly

**Comment by jtydhr88** [comment]
I can reproduce this issue on my end, I will try to fix it this weekend

**Comment by jtydhr88** [comment]
@extra2AB I made a quick fix to disable mask preiview feature which causes this issue for now. you can pull the latest code to try.
![image](https://github.com/jtydhr88/ComfyUI-LayerDivider/assets/860985/2230b9a5-ad8f-4669-92a6-ca3b29a66400)
![image](https://github.com/jtydhr88/ComfyUI-LayerDivider/assets/860985/38fa2d27-a80d-4009-9bb7-a1abd80764c5)
However, I will continue invesigate why feature fails.
thanks for reporting.

**Comment by jtydhr88** [comment]
![image](https://github.com/jtydhr88/ComfyUI-LayerDivider/assets/860985/7299e5f1-38c3-4bcd-8970-ef8288ea6fd7)
this output would not work

**Comment by jtydhr88** [comment]
hey guys, I fixed this issue, thanks for all your help!
![image](https://github.com/jtydhr88/ComfyUI-LayerDivider/assets/860985/a4dc3e00-f995-430a-8c3e-a46ca018fd02)
![image](https://github.com/jtydhr88/ComfyUI-LayerDivider/assets/860985/6c08ada5-363f-44e3-a510-fd2d6e842516)

**Comment by extra2AB** [comment]
Yes.
Can verify, it is working now and the issue is fixed.

Thanks again.
